# version of the configuration.
apiVersion: skaffold/v2beta12
kind: Config
# describes how images are built.
build:
# beta describes how to do a build on the local docker daemon and optionally push to a repository.
  local:
    push: false
  artifacts:
    # the images you're going to be building.
    - image: yauhenisheima/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          # When you see any JS file change, just take that file into the container
          - src: '**/*.js'
            dest: .
          - src: '**/*.css'
            dest: .
          - src: '**/*.html'
            dest: .
deploy:
  kubectl:
    manifest:
    # All the services will be closed automatically with skaffold
      - k8s/*