apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  # Configuration rules
  annotations:
    # We want to create a ingress controller based on the nginx project
    kubernetes.io/ingress.class: 'nginx'
    # Specifies how the copy of nginx behaves: Removes /api
    nginx.ingress.kubernetes.io/user-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
      # We have two different pathes. One leads to client service, the second to the server service
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: client-cluster-ip-service
                port:
                  number: 3000
          - path: /api/?(.*)
            pathType: Prefix
            backend:
              service:
                name: server-cluster-ip-service
                port:
                  number: 5000